<div class="page-header">
    <h1><?php eh('Crear Equipo') ?></h1>
</div>

<div class="span8 span-derecho" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Form::open(NULL, 'post', 'id="form" class="form-horizontal"') ?>
        <?php echo Form::hidden('equipos.id') ?>
        
        <div class="control-group">
            <label class="control-label" for="equipos_nombre">Nombre : </label>
            <div class="controls">
                <?php echo Form::text('equipos.nombre','class="validate[required] text-input"') ?>
                
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="equipos_bandera">Bandera : </label>
            <div class="controls">
                <?php echo Form::text('equipos.bandera','class="validate[required] text-input"') ?>
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="equipos_paises_id">Pais : </label>
            <div class="controls">
                <?php echo Form::dbSelect('equipos.paises_id', 'nombre',null,'Seleccione', 'class="validate[required]"') ?>
            </div>
        </div>
        
        <div class="form-actions">
            <?php echo Form::submit('Guardar', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
        </div>
    <?php echo Form::close() ?>
</div>
<?php 
    Tag::css('validationEngine.jquery');
    echo Html::includeCss();
?>

<?php echo Tag::js('validacion/jquery.validationEngine');?>
<?php echo Tag::js('validacion/jquery.validationEngine-es');?>
<script type="text/javascript" >
    $(function(){
        jQuery("#form").validationEngine();
    });
</script>