<div class="page-header">
    <h1>Listado de Equipos</h1>
</div>
<?php View::content() ?>
<div class="well" style="padding: 8px;border-radius: 2px;">
    <?php echo Html::linkAction('crear', 'Crear Equipo', 'class="btn btn-primary"') ?>
</div>
<?php
//View::partial('backend/barra_superior_listas',FALSE,array('texto' => 'Crear Menú'));
$dt = new DataTable($equipos);
$dt->addHeaders('Nombre', 'Bandera', 'Pais','Estado', 'Editar');
$dt->addFields('nombre', 'bandera', 'paises');
$dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
        'equipos/activar|equipos/desactivar', '', 'activo');
$dt->imgLink('figuras/editar.png', 'equipos/editar');
echo $dt->render('class="table table-bordered table-striped"');
 
?>
