<table class="table table-bordered table-striped">
    <thead>
        <tr style="text-align:center;font-weight:bold;">
            <th colspan="2">Lista de Equipos por Asignar</th>
            </tr>
        <tr style="text-align:center;font-weight:bold;">
            <th></th>
            <th>Nombre Equipo</th>
        </tr>
    </thead>
    <tbody>
        <?php if($equipos){
            foreach ($equipos as $equi) {
        ?>
        
        <tr>
            <td>
               <?php
                    if(in_array($equi->id, $checkEquipos)){
                        echo Form::check("equipos_id", $equi->id,'class="checkequipo"',true);
                    }else{
                        echo Form::check("equipos_id", $equi->id,'class="checkequipo"');
                    }
                    
                ?>
            </td>
            <td>
                <?php echo $equi->nombre?>
            </td>
        </tr>
        <?php 
            }
             echo Form::hidden('torneo_id','',$torneo_id);
        }else{
        ?>
        <tr><td colspan="100">La Consulta no Arrojó Ningun Registro</td></tr>
        <?php }?>
    </tbody>
</table>

<script>

$(document).ready(function (){
   $(".checkequipo").click(function(){
       if($(this).is(":checked")){
            var torneo_id = $('#torneo_id').val();
            $.ajax({
                  type: "POST",
                  url: "<?php echo PUBLIC_PATH . 'torneos/guardarEquipos/'; ?>",
                  data: "equipo_id=" + $(this).val() + "&torneo_id=" + torneo_id + "&tipo="+ 1 
                  
            });
       }else{
           var torneo_id = $('#torneo_id').val();
            $.ajax({
                  type: "POST",
                  url: "<?php echo PUBLIC_PATH . 'torneos/guardarEquipos/'; ?>",
                  data: "equipo_id=" + $(this).val() + "&torneo_id=" + torneo_id + "&tipo="+ 2 
            });
       }
    });
   
});
</script>