<?php
    //View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Agregar', 'opciones' => FALSE));
?>
<table class="table table-bordered table-striped">
    <thead>
        <tr style="text-align:center;font-weight:bold;">
            <th colspan="2">Lista de Equipos por Asignar</th>
            </tr>
        <tr style="text-align:center;font-weight:bold;">
            <th></th>
            <th>Nombre Equipo</th>
        </tr>
    </thead>
    <tbody>
        <?php if($equipos){
            foreach ($equipos as $equi) {
        ?>
        
        <tr>
            <td>
                <!--<input id="equipos_id.<?php echo $equi->id?>" class="checkequipo" name="equipos[]" type="checkbox" value="<?php echo $equi->id?>" />-->
                <?php echo Form::check("equipos_id", $equi->id,'class="checkequipo"')?>
            </td>
            <td>
                <?php echo $equi->nombre?>
            </td>
        </tr>
        <?php 
            }
            echo Html::linkAction('torneos/agregarEquipos', 'Agregar', 'class="btn btn-primary"'); 
        }else{
        ?>
        <tr><td colspan="100">La Consulta no Arrojó Ningun Registro</td></tr>
        <?php }?>
    </tbody>
</table>

<script>

$(document).ready(function (){
   $(".checkequipo").click(function(){
       if($(this).is(":checked")){
           alert($(this).val()+' <-chequeado');
       }else{
           alert($(this).val()+' <-no chequeado');
       }
        
    });
   
});
</script>