<div class="page-header">
    <h1>Listado de Torneos</h1>
</div>

<?php View::content() ?>
<?php
$dt = new DataTable($torneos);
$dt->addHeaders('Logo', 'Nombre', 'Tipo de Torneo', 'Fecha Inicio','Estado', 'Editar','Asignar Equipos');
$dt->addFields(array(
            'field' => 'logo',
            'boolean_field' => false,
            'options' => array(Html::img('%s'))
        ));
$dt->addFields('nombre');
$dt->addFields('tipo_torneo');
$dt->addFields('fecha_ini');
$dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
        'torneos/activar|torneos/desactivar', '', 'activo');
$dt->imgLink('figuras/editar.png', 'torneos/guardar');
$dt->imgLink('figuras/agregar.png', 'torneos/asignar');
echo $dt->render('class="table table-bordered table-striped"');
 
?>
<div class="well" style="padding: 8px;border-radius: 2px;">
    <?php echo Html::linkAction('guardar', 'Crear Torneo', 'class="btn btn-primary"') ?>
</div>